[package]
name = "cdtk-cpu-frag-shader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6.0"
softbuffer = "0.1.1"
winit = "0.27.5"
